# -*- coding: utf-8 -*-
"""answer_evaluator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18L4Zq9GlEdPHSd7M8LHL8bo3mG_H0za6
"""

def evaluate_answer(question, student_answer):
    prompt = f"""
You are a tutor.

Question:
{question}

Student Answer:
{student_answer}

Evaluate the answer.

Rules:
- Say if it's correct, partially correct, or incorrect
- Give a short explanation
- Be supportive, not harsh
"""

    result = pipe(prompt, max_new_tokens=150, temperature=0.6, do_sample=True)

    output = result[0]["generated_text"]
    return output.replace(prompt, "").strip()

question = input("Enter the question: ")
student_answer = input("Enter your answer: ")

feedback = evaluate_answer(question, student_answer)

print("\n📊 Evaluation:\n")
print(feedback)

while True:
    choice = input("\nChoose: tutor / quiz / hint / evaluate / exit: ")

    if choice == "exit":
        break

    elif choice == "quiz":
        topic = input("Topic: ")
        print(generate_quiz(topic))

    elif choice == "hint":
        q = input("Question: ")
        print(generate_hint(q))

    elif choice == "evaluate":
        q = input("Question: ")
        a = input("Your answer: ")
        print(evaluate_answer(q, a))

    elif choice == "tutor":
        q = input("Ask: ")
        # reuse your tutor prompt here