# -*- coding: utf-8 -*-
"""hint_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqJvGDEp0OfhPP7niR553CHop-YNgllG
"""

def generate_hint(question):
    prompt = f"""
You are a helpful tutor.

Give a hint for this question without giving the answer:

{question}

Rules:
- Do NOT reveal the answer
- Keep it short
- Guide the thinking
"""

    result = pipe(prompt, max_new_tokens=80, temperature=0.6, do_sample=True)

    output = result[0]["generated_text"]
    return output.replace(prompt, "").strip()

question = input("Enter your question: ")
hint = generate_hint(question)

print("\n Hint:\n")
print(hint)