# -*- coding: utf-8 -*-
"""improved_prompt_builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxSeuhDPHGBBySQSysJpdbYMKe8kA_P3
"""

# Install (run once)
!pip install -q transformers accelerate torch

# Imports
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import torch

# Clear GPU memory
torch.cuda.empty_cache()

# Model (you can switch if needed)
model_name = "meta-llama/Meta-Llama-3-8B-Instruct"

# Load tokenizer & model
tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto",
    low_cpu_mem_usage=True
)

# Create pipeline
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer
)

# CHAT LOOP (dynamic tutor)
while True:
    user_question = input("\nAsk your question (or type 'exit'): ")

    if user_question.lower() == "exit":
        print("Goodbye")
        break

    # Structured tutor prompt
    prompt = f"""
You are a friendly AI tutor.

Answer the following question:
{user_question}

Rules:
- Use very simple language
- Keep it short
- Break into small steps
- Give ONE real-life example
- Avoid long paragraphs

Structure:
1. Simple Definition
2. Step-by-step Explanation
3. Example
4. Quick Insight
"""

    # Generate answer (memory-safe settings)
    result = pipe(
        prompt,
        max_new_tokens=100,     # keep low to avoid crash
        temperature=0.6,
        do_sample=True,
        eos_token_id=tokenizer.eos_token_id
    )

    # Clean output
    output = result[0]["generated_text"]
    answer = output.replace(prompt, "").strip()

    print("\n Tutor Answer:\n")
    print(answer)







