# -*- coding: utf-8 -*-
"""quiz_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lAnH2_caTeTqc-ZAA-h_BUMf3rWN_Q0
"""

def generate_quiz(topic):
    prompt = f"""
You are a tutor.

Create 3 multiple-choice questions about: {topic}

Rules:
- Each question should have 4 options (A, B, C, D)
- Mark the correct answer
- Keep questions simple
"""

    result = pipe(prompt, max_new_tokens=200, temperature=0.7, do_sample=True)

    output = result[0]["generated_text"]
    return output.replace(prompt, "").strip()

topic = input("Enter topic for quiz: ")
quiz = generate_quiz(topic)

print("\n Quiz:\n")
print(quiz)